ignore some types when ppretty
symonsoft/ppretty pull request #4
Opened 2019-07-17 06:42 UTC by menghuu

ignore some types when ppretty

very useful for showing `pathlib.Path` obj in Config obj

2019-08-05 18:46 UTC, symonsoft requested changes

2019-08-05 18:46 UTC, symonsoft commented on ppretty/ppretty.py
> +    from pathlib import Path
pathlib is only in Python 3. I'm still concerned about compatibility with Python 2

2019-08-05 18:46 UTC, symonsoft commented on ppretty/ppretty.py
> +        if ignore_types is not None and ignore_types is not [None]:
Why do we need checking for [None]?

2019-08-05 18:46 UTC, symonsoft commented on ppretty/ppretty.py
> +                    return [str(current_obj)]
Can be replaced with
```python
if isinstance(current_obj, tuple(ignore_types)):
    return [str(current_obj)]
```

2019-08-24 03:33 UTC, menghuu commented
maybe `ignore_subclasses` should be better than `ignore_types` and there are other features about `ignore_xx` and `force_show_xx`. 

maybe keeping this tool simple is a better idea. so I close this, if I think clearfully about those, I will pull request again

feel free to implement those if you think this necessary

thanks for your review

2019-08-24 03:33 UTC, closed without merging